#!/usr/bin/env node
/**
 * build-data.mjs — data/*.json（単一の真実）から js/data.generated.js を生成する。
 *
 *   data/site.json      … サイト定数・入口データ・診断設問
 *   data/articles.json  … 読み物（spec 002 準拠: sources / target_reader 付き）
 *   data/cases.json     … 事例
 *   data/news.json      … 自動更新ニュース（update-news.mjs が書く）
 *
 * バリデーションに失敗した場合は exit 1（壊れたデータを配信させない）。
 * さらに index.html の <script id="ld-news"> ブロック（JSON-LD）を
 * ニュースの最新状態で書き換える。
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const P = (p) => resolve(ROOT, p);

const fail = (msg) => { console.error(`✗ build-data: ${msg}`); process.exit(1); };
const readJson = (p) => {
  try { return JSON.parse(readFileSync(P(p), "utf8")); }
  catch (e) { fail(`${p} を読めません: ${e.message}`); }
};

// ---------- load ----------
const site = readJson("project/data/site.json");
const articles = readJson("project/data/articles.json");
const cases = readJson("project/data/cases.json");
const news = readJson("project/data/news.json");

// ---------- validate ----------
const req = (obj, keys, label) => {
  for (const k of keys) {
    if (obj[k] === undefined || obj[k] === null || obj[k] === "")
      fail(`${label} に必須フィールド「${k}」がありません: ${JSON.stringify(obj).slice(0, 80)}…`);
  }
};

["issues", "phases", "terms", "questions", "knowledgeCategories"].forEach((k) => {
  if (!Array.isArray(site[k]) || site[k].length === 0) fail(`site.json の ${k} が空です`);
});
site.questions.forEach((q, i) => req(q, ["pillar", "pillarJa", "pillarNum", "q", "options", "weights"], `questions[${i}]`));

if (!Array.isArray(articles.items) || articles.items.length === 0) fail("articles.json の items が空です");
articles.items.forEach((a, i) => {
  req(a, ["num", "cat", "title", "date", "color", "pattern"], `articles[${i}]`);
  // エビデンス原則（001 FR-030 / 002 SC-102）: 出典必須
  if (!Array.isArray(a.sources) || a.sources.length === 0)
    fail(`articles[${i}] (№${a.num}) に sources がありません — 出典なき記事は公開できません`);
  a.sources.forEach((s, j) => req(s, ["key", "title", "author"], `articles[${i}].sources[${j}]`));
});

cases.items.forEach((c, i) => req(c, ["num", "cat", "client", "title", "year", "color", "pattern", "excerpt", "point"], `cases[${i}]`));

if (!Array.isArray(news.items)) fail("news.json の items が配列ではありません");
news.items.forEach((n, i) => {
  req(n, ["id", "date", "cat", "title"], `news[${i}]`);
  if (!n.source || !n.source.name || !n.source.url) fail(`news[${i}] に source(name/url) がありません — 出典なきニュースは掲載できません`);
  if (!n.insight) console.warn(`⚠ news[${i}] (${n.id}) の insight が未執筆です（掲載はされますが示唆なし）`);
});
const urls = news.items.map((n) => n.source.url);
if (new Set(urls).size !== urls.length) fail("news.json に同一URLの重複があります");

// ---------- derive ----------
const latest = articles.items.slice(0, 7); // BRANDRI_LATEST 互換（knowledge 用）
const newsSorted = [...news.items].sort((a, b) => (a.date < b.date ? 1 : -1));

// ---------- emit js/data.generated.js ----------
const banner = `// ============================================================\n// AUTO-GENERATED by scripts/build-data.mjs — 手で編集しない。\n// 編集は project/data/*.json へ。生成: node scripts/build-data.mjs\n// ============================================================\n`;

const js = `${banner}
window.BRANDRI_DATA = ${JSON.stringify({ issues: site.issues, phases: site.phases, terms: site.terms }, null, 2)};

window.BRANDRI_CASES = ${JSON.stringify(cases.items, null, 2)};

// 読み物（全件・最新順）— sources / target_reader 付き（spec 002）
window.BRANDRI_KNOWLEDGE_ALL = ${JSON.stringify(articles.items, null, 2)};

// 互換: 先頭7本
window.BRANDRI_LATEST = ${JSON.stringify(latest, null, 2)};

window.BRANDRI_KNOWLEDGE_CATEGORIES = ${JSON.stringify(site.knowledgeCategories)};

window.BRANDRI_QUESTIONS = ${JSON.stringify(site.questions, null, 2)};

// 自動更新ニュース（scripts/update-news.mjs が data/news.json を更新）
window.BRANDRI_NEWS = ${JSON.stringify(newsSorted, null, 2)};
`;

writeFileSync(P("project/js/data.generated.js"), js);
console.log(`✓ js/data.generated.js を生成（articles:${articles.items.length} / cases:${cases.items.length} / news:${news.items.length}）`);

// ---------- inject JSON-LD (news ItemList) into index.html ----------
const ldPath = P("project/index.html");
let html;
try { html = readFileSync(ldPath, "utf8"); } catch { html = null; }
if (html) {
  const ld = {
    "@context": "https://schema.org",
    "@type": "ItemList",
    "name": "Brandri Daily Briefing — ニュースから読むブランドの論点",
    "itemListElement": newsSorted.slice(0, 9).map((n, i) => ({
      "@type": "ListItem",
      "position": i + 1,
      "item": {
        "@type": "NewsArticle",
        "headline": n.title,
        "datePublished": n.date,
        "url": n.source.url,
        "publisher": { "@type": "Organization", "name": n.source.name },
        "comment": n.insight ? { "@type": "Comment", "text": n.insight, "author": { "@type": "Organization", "name": "Brandri (Highlite Inc.)" } } : undefined
      }
    }))
  };
  const block = `<script type="application/ld+json" id="ld-news">\n${JSON.stringify(ld, null, 2)}\n</script>`;
  const re = /<script type="application\/ld\+json" id="ld-news">[\s\S]*?<\/script>/;
  if (re.test(html)) {
    writeFileSync(ldPath, html.replace(re, block));
    console.log("✓ index.html の JSON-LD (ld-news) を更新");
  } else {
    console.warn("⚠ index.html に id=\"ld-news\" ブロックが見つからないため JSON-LD は未注入");
  }
}
